import Head from 'next/head'
import {useState} from "react"
import Carousel from 'react-bootstrap/Carousel'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
export default function Home({nationalNews}) {

  const [index, setIndex] = useState(0);

  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  return (
  <>
    <Head>
        <title>The India Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
    </Head>

    <div className={styles.container}>

      
      <div id="home">
        <h1 className={styles.title} >
           The India Times <a href="https://nextjs.org">Next.js!</a>
        </h1>
        Menu
      </div>

      <Carousel activeIndex={index} onSelect={handleSelect}>
        {nationalNews.data.map((val)=>(
          <Carousel.Item>
            <a href="https://nextjs.org/docs" className={styles.card} key={val.title}>
            <h2>{val.title} &rarr;</h2>
            <img src={val.imageUrl} width={200}/>
            <p><b>Author:</b> {val.author}</p>
            </a>
          </Carousel.Item>
        ))}
        
     
   
    </Carousel>
    

     
    </div>
  </>
  )
}


export const getStaticProps=async()=>{
  const res=await fetch("https://inshorts.deta.dev/news?category=national")
  .then(res=>res.json())

  return{
    props:{
      nationalNews:res
    }
  }
}
