import Head from "next/head";
import styles from "../styles/Home.module.css";
import NewsCard from "../components/NewsCard";

export default function Home({ worldNews }) {
  console.log(worldNews);
  return (
    <>
      <Head>
        <title>The India Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.grid}>
          {worldNews?.data?.map((val) => (
            <NewsCard 
              key={val.title}
              title={val.title}
              imageUrl={val.imageUrl}
              content={val.content}
              author={val.author}
            />
          ))}
        </div>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://inshorts.deta.dev/news?category=world").then(
    (res) => res.json()
  );

  return {
    props: {
      worldNews: res,
    },
  };
};
