import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({nationalNews}) {
  console.log(nationalNews)
  return (
    <div className={styles.container}>
      <Head>
        <title>The India Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         The India Times <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          {nationalNews.category}{" news"}
        </p>

        <div className={styles.grid}>
        {nationalNews?.data?.map((val)=>(
           <a href="https://nextjs.org/docs" className={styles.card} key={val.title}>
           <h2>{val.title} &rarr;</h2>
           <img src={val.imageUrl} width={200}/>
           <p><b>Author:</b> {val.author}</p>
         </a>
        ))}
          

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps=async()=>{
  let data=[];
  const res=await fetch("https://inshorts.deta.dev/news?category=national")
  .then(res=>res.json())
  .then(res=>{data=res})
  
  return{
    props:{
      nationalNews:data
    }
  }
}